# Generated by Django 5.0.4 on 2024-05-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_model',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('contact_details', models.TextField()),
                ('address', models.TextField()),
                ('vendor_code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quality_rating_avg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_response_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fulfillment_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
